name: firevisor
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.11.0"

dependencies:
  platform: ^3.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.1
  cloud_firestore: ^3.1.0
  firebase_core: ^1.7.0
  firebase_analytics: ^8.3.4
  flutter_ringtone_player: ^3.1.1
  connectivity: ^3.0.6
  wakelock: ^0.5.6
  cloud_functions: ^3.0.0
  firebase_auth: ^3.0.1
  http: ^0.13.1
  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
  flutter_spinkit: ^5.1.0
  fl_chart: ^0.40.2
  timeline_tile: ^2.0.0
  dio: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/alarm.mp3